# Generated by Django 4.2.1 on 2023-05-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_alter_purchase_card_expiration_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cart',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='card_expiration',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
