# Generated by Django 4.2.1 on 2023-05-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_purchase_cart_alter_purchase_card_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
