# Generated by Django 4.2.1 on 2023-05-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
