# Generated by Django 4.2.1 on 2023-05-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='purchase',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cart_items',
            field=models.ManyToManyField(to='store.cartitem'),
        ),
    ]
