# Generated by Django 4.2.1 on 2023-05-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_item_name_cartitem_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cart_items',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
